<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>dev.logicalbytes.enterprise</groupId>
    <artifactId>fizzbuzz-enterprise-parent</artifactId>
    <version>2.0.0-RC7</version>
  </parent>
  <artifactId>fizzbuzz-orchestrator</artifactId>
  <dependencies>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>modulo-computation-service</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>rule-registry-service</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>result-assembly-service</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>feature-flag-service</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>observability-service</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.logicalbytes.enterprise</groupId>
      <artifactId>persistence-and-events-service</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>dev.logicalbytes.enterprise.fizzbuzz.orchestration.FizzBuzzEnterpriseEdition</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
